# Generated by Django 4.2.7 on 2026-06-27 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0008_remove_employeeassignment_conveyance_allowance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0004_delete_clientpayheadtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=20, unique=True)),
                ('location_name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('HEAD_OFFICE', 'Head Office'), ('BRANCH', 'Branch'), ('WAREHOUSE', 'Warehouse'), ('FACTORY', 'Factory'), ('SITE', 'Site'), ('OUTLET', 'Outlet'), ('OTHER', 'Other')], default='BRANCH', max_length=20)),
                ('is_head_office', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Google Maps Latitude', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Google Maps Longitude', max_digits=10, null=True)),
                ('gst_number', models.CharField(blank=True, help_text='GST Number for this location (if different from client)', max_length=15, null=True)),
                ('gst_state', models.CharField(blank=True, help_text='GST State for this location', max_length=50, null=True)),
                ('gst_applicable', models.BooleanField(default=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('auto_billing_enabled', models.BooleanField(default=False, help_text='Enable auto billing for this location')),
                ('commission_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('payment_terms', models.IntegerField(default=30)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_locations', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['client__name', 'location_name'],
                'unique_together': {('client', 'location_code')},
            },
        ),
        migrations.CreateModel(
            name='LocationEmployeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_mappings', to='employees.employeeassignment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_mappings', to='employees.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='locations.location')),
            ],
            options={
                'verbose_name': 'Location Employee Mapping',
                'verbose_name_plural': 'Location Employee Mappings',
                'ordering': ['-start_date'],
                'unique_together': {('employee', 'location', 'start_date')},
            },
        ),
    ]
