# Generated by Django 4.2.7 on 2026-06-24 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('cin_number', models.CharField(blank=True, max_length=21, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pf_applicable', models.BooleanField(default=True)),
                ('pf_employee_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('pf_employer_rate', models.DecimalField(decimal_places=2, default=13.0, max_digits=5)),
                ('pf_capping', models.CharField(choices=[('CAPPED_15000', 'Capped at ₹15,000'), ('CAPPED_18000', 'Capped at ₹18,000'), ('FULL', 'Full Basic'), ('NOT_APPLICABLE', 'Not Applicable')], default='CAPPED_15000', max_length=20)),
                ('esi_applicable', models.BooleanField(default=True)),
                ('esi_employee_rate', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('esi_employer_rate', models.DecimalField(decimal_places=2, default=3.25, max_digits=5)),
                ('esi_limit', models.DecimalField(decimal_places=2, default=21000.0, max_digits=10)),
                ('gst_applicable', models.BooleanField(default=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('gst_type', models.CharField(choices=[('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST')], default='CGST_SGST', max_length=10)),
                ('tds_applicable', models.BooleanField(default=True)),
                ('tds_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('tds_section', models.CharField(default='194C', max_length=20)),
                ('financial_year_start', models.DateField(blank=True, null=True)),
                ('financial_year_end', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('DATA_ENTRY', 'Data Entry'), ('VIEWER', 'Viewer'), ('ACCOUNTANT', 'Accountant'), ('HR', 'HR Manager')], default='VIEWER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('can_create_employee', models.BooleanField(default=False)),
                ('can_edit_employee', models.BooleanField(default=False)),
                ('can_delete_employee', models.BooleanField(default=False)),
                ('can_create_client', models.BooleanField(default=False)),
                ('can_edit_client', models.BooleanField(default=False)),
                ('can_delete_client', models.BooleanField(default=False)),
                ('can_process_payroll', models.BooleanField(default=False)),
                ('can_make_payment', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'role', 'user__username'],
                'unique_together': {('company', 'user')},
            },
        ),
    ]
