# Generated by Django 4.2.7 on 2026-06-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_delete_clientpayheadtemplate'),
        ('employees', '0008_remove_employeeassignment_conveyance_allowance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayheadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('REIMBURSEMENT', 'Reimbursement'), ('BONUS', 'Bonus'), ('ALLOWANCE', 'Allowance'), ('OTHER', 'Other')], default='EARNING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payhead_categories', to='clients.client')),
            ],
            options={
                'verbose_name': 'Payhead Category',
                'verbose_name_plural': 'Payhead Categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('client', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PayheadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('REIMBURSEMENT', 'Reimbursement'), ('BONUS', 'Bonus'), ('ALLOWANCE', 'Allowance'), ('OTHER', 'Other')], default='EARNING', max_length=20)),
                ('code', models.CharField(blank=True, help_text='Short code for reporting', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Basic'), ('PERCENTAGE_GROSS', 'Percentage of Gross'), ('PER_DAY', 'Per Day'), ('PER_UNIT', 'Per Unit'), ('SLAB', 'Slab Based'), ('FORMULA', 'Formula Based')], default='FIXED', max_length=20)),
                ('default_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('formula', models.TextField(blank=True, help_text='Python expression for formula-based calculation')),
                ('is_statutory', models.BooleanField(default=False)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payheads', to='payheads.payheadcategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payhead_templates', to='clients.client')),
            ],
            options={
                'verbose_name': 'Payhead Template',
                'verbose_name_plural': 'Payhead Templates',
                'ordering': ['display_order', 'name'],
                'unique_together': {('client', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentPayheadOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overridden_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('overridden_at', models.DateTimeField(auto_now_add=True)),
                ('overridden_by', models.CharField(blank=True, max_length=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payhead_overrides', to='employees.employeeassignment')),
                ('payhead_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='payheads.payheadtemplate')),
            ],
            options={
                'verbose_name': 'Assignment Payhead Override',
                'verbose_name_plural': 'Assignment Payhead Overrides',
                'ordering': ['payhead_template__display_order'],
                'unique_together': {('assignment', 'payhead_template')},
            },
        ),
    ]
