# Generated by Django 4.2.7 on 2026-06-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payheads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('EARNING', '💚 Earning'), ('DEDUCTION', '❤️ Deduction'), ('STATUTORY_DEDUCTION', '🧡 Statutory Deduction'), ('REIMBURSEMENT', '💙 Reimbursement'), ('LOAN', '💜 Loan'), ('BONUS', '💛 Bonus'), ('ALLOWANCE', '🩵 Allowance')], default='EARNING', max_length=20)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payhead',
                'verbose_name_plural': 'Payheads',
                'ordering': ['type', 'display_order', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='payheadcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='payheadcategory',
            name='client',
        ),
        migrations.AlterUniqueTogether(
            name='payheadtemplate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='payheadtemplate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='payheadtemplate',
            name='client',
        ),
        migrations.DeleteModel(
            name='AssignmentPayheadOverride',
        ),
        migrations.DeleteModel(
            name='PayheadCategory',
        ),
        migrations.DeleteModel(
            name='PayheadTemplate',
        ),
    ]
