# Generated by Django 4.2.7 on 2026-06-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('UNIFORM', 'Uniform'), ('INSURANCE', 'Insurance'), ('MEDICAL', 'Medical'), ('ADVANCE', 'Advance Salary'), ('FESTIVAL', 'Festival Advance'), ('VEHICLE', 'Vehicle Loan'), ('HOME', 'Home Loan'), ('OTHER', 'Other')], max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_installments', models.IntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_installments', models.IntegerField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_installments', models.IntegerField(default=0)),
                ('remaining_installments', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('first_deduction_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='employees.employee')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loantype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField()),
                ('installment_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deducted', models.BooleanField(default=False)),
                ('deducted_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='loans.employeeloan')),
            ],
            options={
                'ordering': ['month_year', 'installment_number'],
                'unique_together': {('employee_loan', 'installment_number')},
            },
        ),
    ]
