# Generated by Django 4.2.7 on 2026-06-24 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeloan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Employee Loan', 'verbose_name_plural': 'Employee Loans'},
        ),
        migrations.AlterModelOptions(
            name='loandeduction',
            options={'ordering': ['month_year', 'installment_number'], 'verbose_name': 'Loan Deduction', 'verbose_name_plural': 'Loan Deductions'},
        ),
        migrations.AlterModelOptions(
            name='loantype',
            options={'ordering': ['name'], 'verbose_name': 'Loan Type', 'verbose_name_plural': 'Loan Types'},
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='last_deduction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loandeduction',
            name='process_voucher_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.processvoucherdetail'),
        ),
        migrations.AddField(
            model_name='loantype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loantype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client associated with this loan (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DEFAULTED', 'Defaulted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loandeduction',
            name='month_year',
            field=models.DateField(help_text='First day of month'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='category',
            field=models.CharField(choices=[('UNIFORM', 'Uniform'), ('INSURANCE', 'Insurance'), ('MEDICAL', 'Medical'), ('ADVANCE', 'Advance Salary'), ('FESTIVAL', 'Festival Advance'), ('VEHICLE', 'Vehicle Loan'), ('HOME', 'Home Loan'), ('EDUCATION', 'Education Loan'), ('PERSONAL', 'Personal Loan'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
