# Generated by Django 4.2.7 on 2026-06-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('loans', '0002_alter_employeeloan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandeduction',
            name='process_voucher_detail',
        ),
        migrations.AddField(
            model_name='loandeduction',
            name='process_voucher_detail_id',
            field=models.IntegerField(blank=True, help_text='Reference to Process Voucher Detail ID', null=True),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
