# Generated by Django 4.2.7 on 2026-06-24 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0004_remove_employee_bonus_remove_employee_conveyance_and_more'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('month_year', models.DateField(help_text='First day of month (e.g., 2024-01-01)')),
                ('total_employees', models.IntegerField(default=0)),
                ('total_present_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_absent_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_production_units', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('PROCESSED', 'Processed')], default='DRAFT', max_length=20)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='attendance_imports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_vouchers', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Voucher',
                'verbose_name_plural': 'Attendance Vouchers',
                'ordering': ['-month_year'],
                'unique_together': {('month_year', 'client')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('error_rows', models.IntegerField(default=0)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('error_details', models.JSONField(default=list)),
                ('attendance_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='attendance.attendancevoucher')),
            ],
            options={
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_present', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('days_absent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('days_leave', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('production_units', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='attendance.attendancevoucher')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance Detail',
                'verbose_name_plural': 'Attendance Details',
                'ordering': ['employee__name'],
                'unique_together': {('attendance_voucher', 'employee')},
            },
        ),
    ]
