# Generated by Django 4.2.7 on 2026-06-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='gst_applicable',
        ),
        migrations.AddField(
            model_name='client',
            name='auto_billing_enabled',
            field=models.BooleanField(default=False, help_text='Enable auto billing for this client'),
        ),
        migrations.AddField(
            model_name='client',
            name='locations',
            field=models.JSONField(blank=True, default=list, help_text='List of client locations'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission rate (in % or fixed amount)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='commission_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount'), ('NONE', 'None')], default='NONE', help_text='Commission calculation type (only if auto billing enabled)', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='gst_state',
            field=models.CharField(blank=True, help_text='GST State for IGST/CGST calculation', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional service charge (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
