# Generated by Django 4.2.7 on 2026-06-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_gst_applicable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPayheadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payhead_templates', to='clients.client')),
            ],
            options={
                'ordering': ['type', 'name'],
                'unique_together': {('client', 'name', 'type')},
            },
        ),
    ]
