# Generated by Django 4.2.7 on 2026-06-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientpayheadtemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientPayheadTemplate',
        ),
    ]
