# Generated by Django 4.2.7 on 2026-06-24 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalTaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='State name', max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Minimum salary for this slab', max_digits=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary for this slab', max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Tax amount for this slab', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professional Tax Slab',
                'verbose_name_plural': 'Professional Tax Slabs',
                'ordering': ['state', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='StatutorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_applicable', models.BooleanField(default=True, help_text='Is PF applicable for this company?')),
                ('pf_employee_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='PF Employee Rate (%)', max_digits=5)),
                ('pf_employer_rate', models.DecimalField(decimal_places=2, default=13.0, help_text='PF Employer Rate (%)', max_digits=5)),
                ('pf_capping', models.CharField(choices=[('CAPPED_15000', 'Capped at ₹15,000'), ('CAPPED_18000', 'Capped at ₹18,000'), ('FULL', 'Full Basic'), ('NOT_APPLICABLE', 'Not Applicable')], default='CAPPED_15000', help_text='PF Capping Rule', max_length=20)),
                ('eps_applicable', models.BooleanField(default=True, help_text='Is EPS applicable?')),
                ('eps_employee_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='EPS Employee Rate (%)', max_digits=5)),
                ('eps_employer_rate', models.DecimalField(decimal_places=2, default=8.33, help_text='EPS Employer Rate (%)', max_digits=5)),
                ('eps_limit', models.DecimalField(decimal_places=2, default=15000.0, help_text='EPS Wage Limit (₹)', max_digits=10)),
                ('esi_applicable', models.BooleanField(default=True, help_text='Is ESI applicable?')),
                ('esi_rule', models.CharField(choices=[('AUTO', 'Auto (If Gross < Limit)'), ('FORCE', 'Force (Always Deduct)'), ('EXEMPT', 'Exempt (Never Deduct)')], default='AUTO', help_text='ESI Deduction Rule', max_length=10)),
                ('esi_limit', models.DecimalField(decimal_places=2, default=21000.0, help_text='ESI Wage Limit (₹)', max_digits=10)),
                ('esi_employee_rate', models.DecimalField(decimal_places=2, default=0.75, help_text='ESI Employee Rate (%)', max_digits=5)),
                ('esi_employer_rate', models.DecimalField(decimal_places=2, default=3.25, help_text='ESI Employer Rate (%)', max_digits=5)),
                ('tds_applicable', models.BooleanField(default=False, help_text='Is TDS applicable?')),
                ('tds_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount (₹)')], default='PERCENTAGE', help_text='TDS Calculation Type', max_length=10)),
                ('tds_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='TDS Rate (%)', max_digits=5)),
                ('tds_section', models.CharField(default='194C', help_text='TDS Section', max_length=20)),
                ('pt_applicable', models.BooleanField(default=True, help_text='Is Professional Tax applicable?')),
                ('pt_state', models.CharField(default='Rajasthan', help_text='State for PT calculation', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statutory Setting',
                'verbose_name_plural': 'Statutory Settings',
            },
        ),
        migrations.CreateModel(
            name='PTChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('year', models.IntegerField()),
                ('state', models.CharField(default='Rajasthan', max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payroll_run_id', models.IntegerField(blank=True, help_text='Reference to Payroll Run ID', null=True)),
                ('generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='statutory/pt/')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='statutory/pt/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year', 'state')},
            },
        ),
        migrations.CreateModel(
            name='PFChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('year', models.IntegerField()),
                ('total_employee_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_employer_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_eps_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_admin_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payroll_run_id', models.IntegerField(blank=True, help_text='Reference to Payroll Run ID', null=True)),
                ('generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='statutory/pf/')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='statutory/pf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ESIChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('year', models.IntegerField()),
                ('total_employee_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_employer_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payroll_run_id', models.IntegerField(blank=True, help_text='Reference to Payroll Run ID', null=True)),
                ('generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='statutory/esi/')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='statutory/esi/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
