# Generated by Django 4.2.7 on 2026-06-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0004_remove_employee_bonus_remove_employee_conveyance_and_more'),
        ('statutory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfchallan',
            name='total_edlis_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pfchallan',
            name='total_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pfchallan',
            name='total_pf_basic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='esichallan',
            name='payroll_run_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pfchallan',
            name='payroll_run_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionaltaxslab',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='professionaltaxslab',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='professionaltaxslab',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professionaltaxslab',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ptchallan',
            name='payroll_run_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='eps_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='eps_employee_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='eps_employer_rate',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=5),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='eps_limit',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='esi_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='esi_employee_rate',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=5),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='esi_employer_rate',
            field=models.DecimalField(decimal_places=2, default=3.25, max_digits=5),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='esi_limit',
            field=models.DecimalField(decimal_places=2, default=21000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='esi_rule',
            field=models.CharField(choices=[('AUTO', 'Auto (If Gross < Limit)'), ('FORCE', 'Force (Always Deduct)'), ('EXEMPT', 'Exempt (Never Deduct)')], default='AUTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='pf_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='pf_capping',
            field=models.CharField(choices=[('CAPPED_15000', 'Capped at ₹15,000'), ('CAPPED_18000', 'Capped at ₹18,000'), ('FULL', 'Full Basic'), ('NOT_APPLICABLE', 'Not Applicable')], default='CAPPED_15000', max_length=20),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='pf_employee_rate',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='pf_employer_rate',
            field=models.DecimalField(decimal_places=2, default=13.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='pt_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='pt_state',
            field=models.CharField(default='Rajasthan', max_length=100),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='tds_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='tds_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='tds_section',
            field=models.CharField(default='194C', max_length=20),
        ),
        migrations.AlterField(
            model_name='statutorysettings',
            name='tds_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount (₹)')], default='PERCENTAGE', max_length=10),
        ),
        migrations.CreateModel(
            name='PFChallanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_code', models.CharField(max_length=20)),
                ('assignment_code', models.CharField(blank=True, max_length=50)),
                ('pf_basic', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employer_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('eps_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='statutory.pfchallan')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'unique_together': {('challan', 'employee')},
            },
        ),
    ]
