# Generated by Django 4.2.7 on 2026-06-24 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loandeduction_process_voucher_detail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0004_remove_employee_bonus_remove_employee_conveyance_and_more'),
        ('clients', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.CharField(max_length=50, unique=True)),
                ('month_year', models.DateField(help_text='First day of month')),
                ('total_employees', models.IntegerField(default=0)),
                ('total_gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pf_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pf_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_eps_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_esi_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_esi_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FINALIZED', 'Finalized'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, help_text='Leave blank for all clients', null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month_year'],
                'unique_together': {('month_year', 'client')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('incentive', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conveyance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('eps_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_basic', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admin_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('edlis_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esi_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esi_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_details', models.JSONField(blank=True, default=dict)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payslips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeeassignment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['employee__name'],
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='client',
        ),
        migrations.RemoveField(
            model_name='paymentvoucherdetail',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='paymentvoucherdetail',
            name='payment_voucher',
        ),
        migrations.RemoveField(
            model_name='paymentvoucherdetail',
            name='process_voucher_detail',
        ),
        migrations.RemoveField(
            model_name='processvoucher',
            name='client',
        ),
        migrations.RemoveField(
            model_name='processvoucherdetail',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='processvoucherdetail',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='processvoucherdetail',
            name='process_voucher',
        ),
        migrations.DeleteModel(
            name='EmployeeLedger',
        ),
        migrations.DeleteModel(
            name='PaymentVoucher',
        ),
        migrations.DeleteModel(
            name='PaymentVoucherDetail',
        ),
        migrations.DeleteModel(
            name='ProcessVoucher',
        ),
        migrations.DeleteModel(
            name='ProcessVoucherDetail',
        ),
    ]
