# Generated by Django 4.2.7 on 2026-06-25 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0004_remove_employee_bonus_remove_employee_conveyance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0002_payrollrun_payslip_remove_paymentvoucher_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('SALARY', 'Salary'), ('ALLOWANCE', 'Allowance'), ('INCENTIVE', 'Incentive'), ('BONUS', 'Bonus'), ('CONVEYANCE', 'Conveyance'), ('LOAN', 'Loan Recovery'), ('ADVANCE', 'Advance'), ('OTHER', 'Other')], default='SALARY', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payable_ledger_id', models.IntegerField(blank=True, help_text='Reference to accounting ledger for debit', null=True)),
                ('bank_ledger_id', models.IntegerField(blank=True, help_text='Reference to accounting ledger for credit', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('accounting_voucher_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('process_voucher_detail_id', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('payment_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll.paymentvoucher')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payslip')),
            ],
            options={
                'ordering': ['employee__name'],
            },
        ),
    ]
