# Generated by Django 4.2.7 on 2026-06-25 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0004_remove_employee_bonus_remove_employee_conveyance_and_more'),
        ('payroll', '0003_paymentvoucher_paymentvoucherdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=50)),
                ('month_year', models.DateField(help_text='First day of month')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('running_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='employees.employee')),
            ],
            options={
                'ordering': ['employee', 'transaction_date', 'created_at'],
                'indexes': [models.Index(fields=['employee', 'transaction_date'], name='payroll_emp_employe_9f2049_idx'), models.Index(fields=['employee', 'month_year'], name='payroll_emp_employe_3c396c_idx'), models.Index(fields=['client', 'month_year'], name='payroll_emp_client__8bf164_idx')],
            },
        ),
    ]
