# Generated by Django 4.2.7 on 2026-06-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('current_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('pf_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('esi_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('uan_number', models.CharField(blank=True, max_length=12, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('pf_override', models.BooleanField(default=False, help_text='Override company PF settings?')),
                ('pf_applicable', models.BooleanField(default=True, help_text='Is PF applicable?')),
                ('pf_employee_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pf_employer_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pf_capping', models.CharField(blank=True, choices=[('CAPPED_15000', 'Capped at ₹15,000'), ('CAPPED_18000', 'Capped at ₹18,000'), ('FULL', 'Full Basic'), ('NOT_APPLICABLE', 'Not Applicable')], max_length=20, null=True)),
                ('esi_override', models.BooleanField(default=False, help_text='Override company ESI settings?')),
                ('esi_applicable', models.BooleanField(default=True)),
                ('esi_employee_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('esi_employer_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('esi_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tds_override', models.BooleanField(default=False)),
                ('tds_applicable', models.BooleanField(default=True)),
                ('tds_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAR', 'Aadhar Card'), ('PAN', 'PAN Card'), ('EDUCATION', 'Education Certificate'), ('PREVIOUS_EMPLOYMENT', 'Previous Employment Record'), ('APPOINTMENT_LETTER', 'Appointment Letter'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('SALARY_SLIP', 'Previous Salary Slip'), ('PHOTO', 'Passport Size Photo'), ('SIGNATURE', 'Signature'), ('OTHER', 'Other')], max_length=50)),
                ('document_file', models.FileField(upload_to='employee_documents/')),
                ('document_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('salary_method', models.CharField(choices=[('CALENDAR_MONTH', 'Calendar Month'), ('26_DAYS_MONTH', '26-Days Month'), ('PER_DAY', 'Per Day'), ('PRODUCTION', 'Production')], default='CALENDAR_MONTH', max_length=20)),
                ('monthly_basic', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_day_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_cap', models.CharField(choices=[('CAPPED_15000', 'Capped at ₹15,000'), ('CAPPED_18000', 'Capped at ₹18,000'), ('FULL', 'Full Basic'), ('NOT_APPLICABLE', 'Not Applicable')], default='CAPPED_15000', max_length=20)),
                ('esi_rule', models.CharField(choices=[('AUTO', 'Auto'), ('FORCE', 'Force'), ('EXEMPT', 'Exempt')], default='AUTO', max_length=10)),
                ('professional_tax_exempt', models.BooleanField(default=False)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='clients.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
