# Generated by Django 4.2.7 on 2026-06-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='default_monthly_basic',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default monthly basic salary', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_per_day_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default per day rate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_salary_method',
            field=models.CharField(choices=[('CALENDAR_MONTH', 'Calendar Month'), ('26_DAYS_MONTH', '26-Days Month'), ('PER_DAY', 'Per Day'), ('PRODUCTION', 'Production')], default='CALENDAR_MONTH', help_text='Default salary calculation method', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esi_applicable',
            field=models.BooleanField(default=True, help_text='Is ESI applicable for this employee?'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esi_employee_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ESI Employee Rate (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esi_employer_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ESI Employer Rate (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esi_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ESI Wage Limit (₹)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf_applicable',
            field=models.BooleanField(default=True, help_text='Is PF applicable for this employee?'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf_capping',
            field=models.CharField(blank=True, choices=[('CAPPED_15000', 'Capped at ₹15,000'), ('CAPPED_18000', 'Capped at ₹18,000'), ('FULL', 'Full Basic'), ('NOT_APPLICABLE', 'Not Applicable')], help_text='PF Capping Rule', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf_employee_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PF Employee Rate (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf_employer_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PF Employer Rate (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tds_applicable',
            field=models.BooleanField(default=True, help_text='Is TDS applicable for this employee?'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tds_override',
            field=models.BooleanField(default=False, help_text='Override company TDS settings?'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tds_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TDS Rate (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('AADHAR', 'Aadhar Card'), ('PAN', 'PAN Card'), ('EDUCATION', 'Education Certificate'), ('PREVIOUS_EMPLOYMENT', 'Previous Employment Record'), ('APPOINTMENT_LETTER', 'Appointment Letter'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('SALARY_SLIP', 'Previous Salary Slip'), ('PHOTO', 'Passport Size Photo'), ('SIGNATURE', 'Signature'), ('BANK_STATEMENT', 'Bank Statement'), ('PF_CARD', 'PF Card'), ('ESI_CARD', 'ESI Card'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
