# Generated by Django 4.2.7 on 2026-06-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_default_monthly_basic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='default_monthly_basic',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='default_per_day_rate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='default_salary_method',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esi_override',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pf_override',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tds_override',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tds_rate',
        ),
        migrations.AddField(
            model_name='employee',
            name='advance_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='conveyance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='da',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Dearness Allowance', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='eps_applicable',
            field=models.BooleanField(default=True, help_text='Is EPS (Pension) applicable for this employee?'),
        ),
        migrations.AddField(
            model_name='employee',
            name='eps_employee_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='EPS Employee Rate (%) - Usually 0%', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='eps_employer_rate',
            field=models.DecimalField(decimal_places=2, default=8.33, help_text='EPS Employer Rate (%) - Usually 8.33%', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='eps_limit',
            field=models.DecimalField(decimal_places=2, default=15000.0, help_text='EPS Wage Limit (₹) - Usually ₹15,000', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='esi_rule',
            field=models.CharField(choices=[('AUTO', 'Auto (If Gross < ₹21,000)'), ('FORCE', 'Force (Always Deduct)'), ('EXEMPT', 'Exempt (Never Deduct)')], default='AUTO', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='House Rent Allowance', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='incentive',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='loan_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='lta',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Leave Travel Allowance', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='tds_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount (₹)')], default='PERCENTAGE', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='tds_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='TDS Rate (%) or Fixed Amount (₹)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esi_employee_rate',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esi_employer_rate',
            field=models.DecimalField(decimal_places=2, default=3.25, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esi_limit',
            field=models.DecimalField(decimal_places=2, default=21000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf_capping',
            field=models.CharField(choices=[('CAPPED_15000', 'Capped at ₹15,000'), ('CAPPED_18000', 'Capped at ₹18,000'), ('FULL', 'Full Basic'), ('NOT_APPLICABLE', 'Not Applicable')], default='CAPPED_15000', help_text='PF Capping Rule', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf_employee_rate',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='PF Employee Rate (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf_employer_rate',
            field=models.DecimalField(decimal_places=2, default=13.0, help_text='PF Employer Rate (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tds_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('AADHAR', 'Aadhar Card'), ('PAN', 'PAN Card'), ('EDUCATION_10TH', '10th Certificate'), ('EDUCATION_12TH', '12th Certificate'), ('EDUCATION_GRADUATION', 'Graduation Certificate'), ('EDUCATION_POST_GRADUATION', 'Post Graduation Certificate'), ('PREVIOUS_EMPLOYMENT', 'Previous Employment Letter'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('SALARY_SLIP', 'Previous Salary Slip'), ('APPOINTMENT_LETTER', 'Appointment Letter'), ('PHOTO', 'Passport Size Photo'), ('SIGNATURE', 'Signature'), ('BANK_STATEMENT', 'Bank Statement'), ('PF_CARD', 'PF Card'), ('ESI_CARD', 'ESI Card'), ('MEDICAL', 'Medical Certificate'), ('POLICE_VERIFICATION', 'Police Verification'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
