# Generated by Django 4.2.7 on 2026-06-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_default_monthly_basic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='conveyance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='da',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='incentive',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lta',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='medical_allowance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='other_earnings',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='overtime',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='special_allowance',
        ),
        migrations.AddField(
            model_name='employee',
            name='dynamic_deductions',
            field=models.JSONField(blank=True, default=dict, help_text="Dynamic deductions (e.g., {'Insurance': 1000, 'Professional Tax': 200, 'Union Fee': 100})"),
        ),
        migrations.AddField(
            model_name='employee',
            name='dynamic_salary_heads',
            field=models.JSONField(blank=True, default=dict, help_text="Dynamic salary heads (e.g., {'Bonus': 5000, 'Incentive': 2000, 'Special Allowance': 3000})"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='advance_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Advance Deduction (Fixed)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Basic Pay (Fixed)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eps_employee_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='EPS Employee Rate (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eps_employer_rate',
            field=models.DecimalField(decimal_places=2, default=8.33, help_text='EPS Employer Rate (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eps_limit',
            field=models.DecimalField(decimal_places=2, default=15000.0, help_text='EPS Wage Limit (₹)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esi_employee_rate',
            field=models.DecimalField(decimal_places=2, default=0.75, help_text='ESI Employee Rate (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esi_employer_rate',
            field=models.DecimalField(decimal_places=2, default=3.25, help_text='ESI Employer Rate (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esi_limit',
            field=models.DecimalField(decimal_places=2, default=21000.0, help_text='ESI Wage Limit (₹)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esi_rule',
            field=models.CharField(choices=[('AUTO', 'Auto (If Gross < ₹21,000)'), ('FORCE', 'Force (Always Deduct)'), ('EXEMPT', 'Exempt (Never Deduct)')], default='AUTO', help_text='ESI Rule', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='House Rent Allowance (Fixed)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='loan_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Loan Deduction (Fixed)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Professional Tax', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tds_applicable',
            field=models.BooleanField(default=False, help_text='Is TDS applicable for this employee?'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tds_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount (₹)')], default='PERCENTAGE', help_text='TDS Type', max_length=10),
        ),
    ]
