# Generated by Django 4.2.7 on 2026-06-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_bonus_remove_employee_conveyance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='master_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
