# Generated by Django 4.2.7 on 2026-06-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_master_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Date from which this assignment is effective', null=True),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='esi_rule',
            field=models.CharField(choices=[('AUTO', 'Auto (If Gross < ₹21,000)'), ('FORCE', 'Force (Always Deduct)'), ('EXEMPT', 'Exempt (Never Deduct)')], default='AUTO', max_length=10),
        ),
    ]
