# Generated by Django 4.2.7 on 2026-06-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeeassignment_effective_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='eps_applicable',
            field=models.BooleanField(default=True, help_text='Is EPS (Pension) applicable for this assignment?'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='eps_employer_rate',
            field=models.DecimalField(decimal_places=2, default=8.33, help_text='EPS Employer Rate (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='eps_limit',
            field=models.DecimalField(decimal_places=2, default=15000.0, help_text='EPS Wage Limit (₹)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
