# Generated by Django 4.2.7 on 2026-06-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeeassignment_eps_applicable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeassignment',
            name='conveyance_allowance',
        ),
        migrations.RemoveField(
            model_name='employeeassignment',
            name='other_allowance',
        ),
        migrations.RemoveField(
            model_name='employeeassignment',
            name='special_allowance',
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='salary_heads',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic salary heads'),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='eps_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='eps_employer_rate',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='eps_limit',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=10),
        ),
    ]
