# Generated by Django 4.2.7 on 2026-06-27 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('employees', '0008_remove_employeeassignment_conveyance_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location where employee works', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='locations.location'),
        ),
    ]
